### ISSUE TITLE
Select2 - single-value select, min-width style

### ISSUE THREAD

**Issue by jansura** [riganti/dotvvm-contrib#17]
Hi,

I was wondering if there is a chance to add a single-value picker to the existing Select2 multi-select control?

Also I was unable to set min-width to the multi-select control but that's most likely due to my inexperience with dotvvm in general - is there any way to set the width without changing the stylesheet? It looks really weird when no values are selected :)

![dotvvm-select2](https://user-images.githubusercontent.com/30835343/42641510-fec1e22a-85f4-11e8-89c2-cc938dc925a8.JPG)

Thanks!

**Comment by adamjez** [comment]
The width (or min-width) of the select can be changed only with styles, eg: `style="width: xpx"`.

It would be nice to have single value **Select2** and it's pretty simple to implement. But it can't be implemented as part of the `Select2` DotVVM Control because the control inherits from `MultiSelectHtmlControlBase` which contains `SelectedValues` property. Because of this, It has to be separate control and I can't think of any name for this control. What name do you suggest? @jansura @quigamdev @tomasherceg

**Comment by quigamdev** [comment]
@adamjez  I think <dc:SingleSelect2 /> could be ok.

**Comment by tomasherceg** [comment]
Hmm, Select2 is not a good name for a library. :-(

I would prefer having `<dc:Select2Single>` so the name woult still start with Select2.
